services:
  test:
    image: ubuntu
    deploy:
      resources:
        reservations:
          devices:
            # this seems to work with podman-compose
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]     
